model:
  model_name: 'llava-med-7b-mpt'
  # model_path: './playground/model_weights/llava-v1.5-7b'
  model_path: 'liuhaotian/LLaVA-Lightning-MPT-7B-preview'

parameters:
  sep: ','
  temperature: 0
  top_p: None
  num_beams: 1
  max_new_tokens: 256